[SERVICE]
    Daemon       off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name        tail
    Path        /var/log/nginx/*.log
    Tag         nginx
    Skip_Long_Lines On
    Refresh_Interval 5

[OUTPUT]
    Name        es
    Match       *
    Host        elasticsearch
    Port        9200
    Index       nginx-logs
    Suppress_Type_Name On
    Generate_ID On

[OUTPUT]
    Name        stdout
    Match       *
    Format      json


