version: '3.7'

services:
  fluentbeat:
    image: fluent/fluent-bit:latest
    container_name: fluentbeat
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    user: root
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/log/nginx:/var/log/nginx:ro
    networks:
      - elk-network
    depends_on:
      - elasticsearch
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:7.17.0
    volumes:
      - ./configs/elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "test"
      discovery.type: single-node
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:7.17.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    volumes:
      - ./configs/kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - elk
    ports:
      - "5601:5601"


  beats:
    image: elastic/filebeat:7.16.2
    volumes:
      - ./configs/filebeat/config.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./host_metrics_app/:/host_metrics_app/:ro
      - ./log_gen/:/log_gen/:ro
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
